/**
 * singlish.js
 *
 * A real Singlish/Colloquial-Singapore-English lexicon. The core insight this
 * module encodes: in Singlish, HOW something is said — particle choice,
 * stacking, reduplication, clause-final markers — is often the actual
 * emotional content, while the lexical (content) words look neutral to a
 * naive sentiment reader. A model scoring sentiment off content words alone
 * systematically produces false negatives on masked distress, which in a
 * wellbeing app is the dangerous direction.
 *
 * Singlish has no fixed orthography, so most entries carry spelling variants
 * (sian/siann, paiseh/pai seh, walao/wah lao, etc).
 *
 * Each entry:
 *   - token: canonical form
 *   - variants: alternate spellings/forms that should also match
 *   - category: "particle" | "vocabulary" | "aspect" | "reduplication"
 *   - gloss: plain-English meaning / function
 *   - stance: what the speaker is signalling (for particles), or null
 *   - valenceShift: nudge to apply to valence in [-1, 1], negative = sadder
 *   - arousalShift: nudge to apply to arousal in [-1, 1]
 *   - masksDistress: true when this token is a classic vehicle for
 *     understating or hiding real distress behind neutral-looking words —
 *     the false-negative risk this whole module exists to catch.
 */

export const SINGLISH_LEXICON_VERSION = "singlish-2026.10-contextual-3";

export const SINGLISH_LEXICON = Object.freeze([
  // ── Particles ──────────────────────────────────────────────────────────
  {
    token: "lah",
    variants: ["lah", "la"],
    category: "particle",
    gloss: "softener or assertion marker; tone-dependent",
    stance: "assertive-softener",
    valenceShift: 0,
    arousalShift: 0,
    masksDistress: false,
  },
  {
    token: "fine lah",
    variants: ["fine lah", "fine la", "i'm fine lah", "im fine lah"],
    category: "particle",
    gloss: "'fine' clause-closed with lah — often a resigned, drop-it fine rather than genuine reassurance",
    stance: "resigned-closure",
    valenceShift: -0.35,
    arousalShift: -0.1,
    masksDistress: true,
  },
  {
    token: "leh",
    variants: ["leh"],
    category: "particle",
    gloss: "mild appeal, contrastive emphasis, or plaintive request for consideration",
    stance: "plaintive-appeal",
    valenceShift: 0,
    arousalShift: 0,
    masksDistress: false,
  },
  {
    token: "lor",
    variants: ["lor", "lorh"],
    category: "particle",
    gloss: "marks an outcome as obvious, expected, or accepted; it can sound resigned, but text without intonation/context cannot determine that by itself",
    stance: "obvious-or-accepted-outcome",
    valenceShift: 0,
    arousalShift: 0,
    masksDistress: false,
  },
  {
    token: "meh",
    variants: ["meh"],
    category: "particle",
    gloss: "sceptical or challenging question marker",
    stance: "sceptical-challenge",
    valenceShift: 0,
    arousalShift: 0.1,
    masksDistress: false,
  },
  {
    token: "hor",
    variants: ["hor"],
    category: "particle",
    gloss: "seeking agreement / confirmation, sometimes a soft warning",
    stance: "seeking-confirmation",
    valenceShift: 0,
    arousalShift: 0,
    masksDistress: false,
  },
  {
    token: "sia",
    variants: ["sia", "siah"],
    category: "particle",
    gloss: "intensifier for exasperation, awe, excitement, or overwhelm; surrounding content supplies the emotional direction",
    stance: "intensifier",
    valenceShift: 0,
    arousalShift: 0.3,
    masksDistress: false,
  },
  {
    token: "ah",
    variants: ["ah"],
    category: "particle",
    gloss: "softening question tag or filler; low signal alone",
    stance: "softener",
    valenceShift: 0,
    arousalShift: 0,
    masksDistress: false,
  },
  {
    token: "sian ah",
    variants: ["sian ah", "sian sia", "siann ah"],
    category: "particle",
    gloss: "'sian' intensified with a clause-final marker — jadedness stated directly, often the real payload of an otherwise practical sentence",
    stance: "jaded-statement",
    valenceShift: -0.5,
    arousalShift: -0.25,
    masksDistress: true,
  },
  {
    token: "nvm lor",
    variants: ["nvm lor", "never mind lor", "nvm lorh"],
    category: "particle",
    gloss: "a never-mind dismissal closed as an accepted outcome; often conveys resignation rather than genuine resolution",
    stance: "resigned-dismissal",
    valenceShift: -0.4,
    arousalShift: -0.15,
    masksDistress: true,
  },
  {
    token: "no choice lor",
    variants: ["no choice lor", "no choice lorh", "bo bian lor", "bo pian lor"],
    category: "particle",
    gloss: "accepting an unwanted outcome because the speaker sees no available choice",
    stance: "constrained-resignation",
    valenceShift: -0.45,
    arousalShift: -0.1,
    masksDistress: true,
  },
  {
    token: "one",
    variants: ["one"],
    category: "particle",
    gloss: "clause-final nominaliser/emphasis marker ('very stress one' = 'is very stressful'); NOT the number one or an article",
    stance: "emphatic-nominaliser",
    valenceShift: 0,
    arousalShift: 0,
    masksDistress: false,
  },
  {
    token: "sial",
    variants: ["sial", "siol", "seh"],
    category: "particle",
    gloss: "strong intensifier, often frustration or disbelief; casual/vulgar register",
    stance: "strong-intensifier",
    valenceShift: -0.2,
    arousalShift: 0.35,
    masksDistress: false,
  },
  {
    token: "wah",
    variants: ["wah", "wahh"],
    category: "particle",
    gloss: "attention-getting surprise, admiration, shock, or exasperation; the surrounding proposition supplies direction",
    stance: "surprised-attention",
    valenceShift: 0,
    arousalShift: 0.2,
    masksDistress: false,
  },
  {
    token: "sibei",
    variants: ["sibei", "si bei"],
    category: "particle",
    gloss: "strong degree intensifier roughly 'extremely'; it amplifies the following positive or negative expression",
    stance: "degree-intensifier",
    valenceShift: 0,
    arousalShift: 0.18,
    masksDistress: false,
  },
  {
    token: "where got",
    variants: ["where got", "where got sia", "where got one"],
    category: "particle",
    gloss: "challenging denial meaning that the claimed situation is not true",
    stance: "challenging-denial",
    valenceShift: 0,
    arousalShift: 0.12,
    masksDistress: false,
  },
  {
    token: "can or not",
    variants: ["can or not", "can anot", "can or cannot"],
    category: "particle",
    gloss: "requests a definite answer or compliance; impatience depends on surrounding wording",
    stance: "answer-seeking",
    valenceShift: 0,
    arousalShift: 0.08,
    masksDistress: false,
  },

  // ── Emotional vocabulary ────────────────────────────────────────────────
  {
    token: "damn sian",
    variants: ["damn sian", "damn sianz", "very sian", "very sianz", "so sian", "so sianz"],
    category: "vocabulary",
    gloss: "strongly fed up and low on motivation; often combines reluctance with irritation rather than sadness",
    stance: "intensified-task-aversion",
    valenceShift: -0.55,
    arousalShift: 0.05,
    masksDistress: true,
  },
  {
    token: "sian",
    variants: ["sian", "siann", "sianz", "sienz", "syen"],
    category: "vocabulary",
    gloss: "jaded, demotivated, fed up, bored-of-life — the actual emotional payload in sentences that otherwise read as neutral scheduling or complaint",
    stance: null,
    valenceShift: -0.45,
    arousalShift: -0.2,
    masksDistress: true,
  },
  {
    token: "damn shag",
    variants: ["damn shag", "sibei shag", "very shag", "so shag"],
    category: "vocabulary",
    gloss: "strongly exhausted and worn down, sometimes with fed-up frustration",
    stance: "intensified-exhaustion",
    valenceShift: -0.52,
    arousalShift: -0.25,
    masksDistress: true,
  },
  {
    token: "bo bian",
    variants: ["bo bian", "bo pian"],
    category: "vocabulary",
    gloss: "there is no alternative; constrained, reluctant acceptance rather than neutral agreement",
    stance: "constrained-resignation",
    valenceShift: -0.38,
    arousalShift: -0.08,
    masksDistress: true,
  },
  {
    token: "lan lan",
    variants: ["lan lan", "llst", "lan lan suck thumb"],
    category: "vocabulary",
    gloss: "reluctantly accepting an unwanted situation because no useful choice seems available",
    stance: "resentful-resignation",
    valenceShift: -0.42,
    arousalShift: 0.02,
    masksDistress: true,
  },
  {
    token: "dulan",
    variants: ["dulan", "du lan", "tulan", "tu lan"],
    category: "vocabulary",
    gloss: "angry, irritated, or intensely fed up",
    stance: "irritated-anger",
    valenceShift: -0.48,
    arousalShift: 0.48,
    masksDistress: false,
  },
  {
    token: "paiseh",
    variants: ["paiseh", "pai seh", "pai sei"],
    category: "vocabulary",
    gloss: "embarrassment and shame, far more socially loaded than 'sorry' — carries real face/social-standing weight, not simple politeness",
    stance: null,
    valenceShift: -0.35,
    arousalShift: 0.15,
    masksDistress: true,
  },
  {
    token: "shiok",
    variants: ["shiok", "syok"],
    category: "vocabulary",
    gloss: "extremely satisfying/pleasurable, strongly positive",
    stance: null,
    valenceShift: 0.6,
    arousalShift: 0.3,
    masksDistress: false,
  },
  {
    token: "shag",
    variants: ["shag", "shagged"],
    category: "vocabulary",
    gloss: "exhausted, worn out (Singlish usage; NOT the vulgar British sense)",
    stance: null,
    valenceShift: -0.35,
    arousalShift: -0.3,
    masksDistress: true,
  },
  {
    token: "blur",
    variants: ["blur", "blur like sotong"],
    category: "vocabulary",
    gloss: "confused, disoriented, not keeping up",
    stance: null,
    valenceShift: -0.15,
    arousalShift: -0.1,
    masksDistress: false,
  },
  {
    token: "chope",
    variants: ["chope", "chop"],
    category: "vocabulary",
    gloss: "to reserve a spot/seat in advance (e.g. with tissue packets) — neutral, practical",
    stance: null,
    valenceShift: 0,
    arousalShift: 0,
    masksDistress: false,
  },
  {
    token: "walao",
    variants: ["walao", "wah lao", "walau", "wah lau"],
    category: "vocabulary",
    gloss: "exclamation of exasperation, disbelief, or frustration",
    stance: null,
    valenceShift: -0.3,
    arousalShift: 0.35,
    masksDistress: false,
  },
  {
    token: "buay tahan",
    variants: ["buay tahan", "boh tahan", "bo tahan", "cannot tahan"],
    category: "vocabulary",
    gloss: "'can't stand it/take it anymore' — a direct statement of being at one's limit",
    stance: null,
    valenceShift: -0.55,
    arousalShift: 0.25,
    masksDistress: false,
  },
  {
    token: "jialat",
    variants: ["jialat", "jia lat"],
    category: "vocabulary",
    gloss: "in trouble, in a bad/dire state",
    stance: null,
    valenceShift: -0.5,
    arousalShift: 0.2,
    masksDistress: false,
  },
  {
    token: "kancheong",
    variants: ["kancheong", "kan cheong", "kanchiong"],
    category: "vocabulary",
    gloss: "anxious, flustered, in a rushed panic",
    stance: null,
    valenceShift: -0.4,
    arousalShift: 0.5,
    masksDistress: false,
  },
  {
    token: "bo chup",
    variants: ["bo chup", "boh chup"],
    category: "vocabulary",
    gloss: "'don't care' — can be genuine indifference or a defensive, checked-out withdrawal",
    stance: null,
    valenceShift: -0.2,
    arousalShift: -0.2,
    masksDistress: true,
  },
  {
    token: "catch no ball",
    variants: ["catch no ball", "catch no balls"],
    category: "vocabulary",
    gloss: "completely failing to understand what's going on",
    stance: null,
    valenceShift: -0.15,
    arousalShift: 0,
    masksDistress: false,
  },
  {
    token: "atas",
    variants: ["atas"],
    category: "vocabulary",
    gloss: "high-class, snobbish, upscale — can be admiring or mocking",
    stance: null,
    valenceShift: 0,
    arousalShift: 0,
    masksDistress: false,
  },
  {
    token: "sabo",
    variants: ["sabo", "sabo king", "saboed"],
    category: "vocabulary",
    gloss: "to sabotage or set someone up, often in a mischievous/betrayed sense",
    stance: null,
    valenceShift: -0.3,
    arousalShift: 0.2,
    masksDistress: false,
  },
  {
    token: "steady",
    variants: ["steady", "steady lah"],
    category: "vocabulary",
    gloss: "reliable, impressive, dependable — approval",
    stance: null,
    valenceShift: 0.35,
    arousalShift: 0.1,
    masksDistress: false,
  },
  {
    token: "can lah",
    variants: ["can lah", "can la"],
    category: "vocabulary",
    gloss: "affirmative, agreeable — 'it's fine/doable'",
    stance: null,
    valenceShift: 0.15,
    arousalShift: -0.05,
    masksDistress: false,
  },
  {
    token: "cannot make it",
    variants: ["cannot make it", "cant make it", "can't make it"],
    category: "vocabulary",
    gloss: "declining/cancelling — on its own just a scheduling statement, but check for a co-occurring particle/emotion word (e.g. 'sian') carrying the real reason",
    stance: null,
    valenceShift: 0,
    arousalShift: 0,
    masksDistress: false,
  },
  {
    token: "nvm",
    variants: ["nvm", "never mind"],
    category: "vocabulary",
    gloss: "'never mind' — on its own neutral, but when closed with 'lor' becomes resigned dismissal rather than genuine letting-go",
    stance: null,
    valenceShift: -0.1,
    arousalShift: -0.1,
    masksDistress: true,
  },
  {
    token: "used to it",
    variants: ["used to it", "used to it already", "used to it liao"],
    category: "vocabulary",
    gloss: "habituation to a bad situation — reads as acceptance but often signals prolonged, normalised hurt",
    stance: null,
    valenceShift: -0.3,
    arousalShift: -0.15,
    masksDistress: true,
  },
  {
    token: "stress one",
    variants: ["stress one", "very stress one", "so stress one"],
    category: "vocabulary",
    gloss: "topic-prominent construction with dropped copula and 'stress' used as an adjective — a direct self-report of emotional/mental strain that parsers miss because there is no verb 'to be feel stressed'",
    stance: null,
    valenceShift: -0.4,
    arousalShift: 0.3,
    masksDistress: true,
  },

  {
    token: "alamak",
    variants: ["alamak", "aiyah", "aiya", "aiyoh", "aiyo"],
    category: "vocabulary",
    gloss: "exclamation of dismay, exasperation, or mild shock",
    stance: null,
    valenceShift: -0.25,
    arousalShift: 0.3,
    masksDistress: false,
  },
  {
    token: "haiz",
    variants: ["haiz", "hais", "haiss", "haiyo", "haiyah"],
    category: "vocabulary",
    gloss: "written sigh signalling disappointment, weariness, resignation, or exasperation",
    stance: "sigh",
    valenceShift: -0.3,
    arousalShift: -0.15,
    masksDistress: true,
  },
  {
    token: "pek chek",
    variants: ["pek chek", "pekcek", "pek chek sia"],
    category: "vocabulary",
    gloss: "frustrated, irritated, or pent-up from an aggravating situation",
    stance: null,
    valenceShift: -0.4,
    arousalShift: 0.4,
    masksDistress: false,
  },
  {
    token: "rabak",
    variants: ["rabak", "rabak sia"],
    category: "vocabulary",
    gloss: "in a bad, difficult, or badly messed-up state",
    stance: null,
    valenceShift: -0.4,
    arousalShift: 0.15,
    masksDistress: false,
  },
  {
    token: "song",
    variants: ["song", "song ah", "song sia"],
    category: "vocabulary",
    gloss: "deeply enjoyable, satisfying, or pleasurable in the present moment",
    stance: null,
    valenceShift: 0.55,
    arousalShift: 0.2,
    masksDistress: false,
  },
  {
    token: "siao",
    variants: ["siao", "siow"],
    category: "vocabulary",
    gloss: "crazy/mad — describing a situation, person, or oneself as overwhelmed to the point of craziness",
    stance: null,
    valenceShift: -0.3,
    arousalShift: 0.4,
    masksDistress: false,
  },
  {
    token: "kiasu",
    variants: ["kiasu", "kia su"],
    category: "vocabulary",
    gloss: "fear of losing out; anxious competitiveness",
    stance: null,
    valenceShift: -0.2,
    arousalShift: 0.3,
    masksDistress: false,
  },
  {
    token: "kiasi",
    variants: ["kiasi", "kia si"],
    category: "vocabulary",
    gloss: "fear of dying/failing; overly cautious out of anxiety",
    stance: null,
    valenceShift: -0.2,
    arousalShift: 0.25,
    masksDistress: false,
  },
  {
    token: "heng",
    variants: ["heng ah", "heng"],
    category: "vocabulary",
    gloss: "lucky, relieved that something bad was avoided",
    stance: null,
    valenceShift: 0.35,
    arousalShift: 0.15,
    masksDistress: false,
  },
  {
    token: "suay",
    variants: ["suay", "swee suay"],
    category: "vocabulary",
    gloss: "unlucky, unfortunate",
    stance: null,
    valenceShift: -0.3,
    arousalShift: 0.1,
    masksDistress: false,
  },
  {
    token: "lepak",
    variants: ["lepak", "lepaking"],
    category: "vocabulary",
    gloss: "to relax/chill/hang out idly — generally positive, low-arousal",
    stance: null,
    valenceShift: 0.25,
    arousalShift: -0.3,
    masksDistress: false,
  },
  {
    token: "bojio",
    variants: ["bojio", "bo jio"],
    category: "vocabulary",
    gloss: "'didn't invite (me)' — playful complaint, can mask genuine feeling of exclusion",
    stance: null,
    valenceShift: -0.15,
    arousalShift: 0.1,
    masksDistress: true,
  },
  {
    token: "malu",
    variants: ["malu"],
    category: "vocabulary",
    gloss: "embarrassed/ashamed (Malay-derived, used interchangeably with paiseh in some circles)",
    stance: null,
    valenceShift: -0.3,
    arousalShift: 0.15,
    masksDistress: true,
  },
  {
    token: "geram",
    variants: ["geram", "gerammm"],
    category: "vocabulary",
    gloss: "frustrated/irritated to the point of wanting to squeeze/pinch something",
    stance: null,
    valenceShift: -0.35,
    arousalShift: 0.4,
    masksDistress: false,
  },
  {
    token: "tekan",
    variants: ["tekan", "kena tekan"],
    category: "vocabulary",
    gloss: "to pressure/bully someone, or being pressured/bullied",
    stance: null,
    valenceShift: -0.5,
    arousalShift: 0.3,
    masksDistress: false,
  },
  {
    token: "kena",
    variants: ["kena", "kenna"],
    category: "vocabulary",
    gloss: "passive-voice marker for something bad happening to you ('kena scolded' = 'got scolded')",
    stance: "passive-affliction",
    valenceShift: -0.25,
    arousalShift: 0.15,
    masksDistress: false,
  },
  {
    token: "gone case",
    variants: ["gone case", "confirm gone case"],
    category: "vocabulary",
    gloss: "hopeless, beyond saving — can be humorous or genuinely despairing depending on context",
    stance: null,
    valenceShift: -0.45,
    arousalShift: -0.1,
    masksDistress: true,
  },
  {
    token: "cheem",
    variants: ["cheem", "chim"],
    category: "vocabulary",
    gloss: "overly complex, hard to understand",
    stance: null,
    valenceShift: -0.1,
    arousalShift: 0,
    masksDistress: false,
  },
  {
    token: "zhun",
    variants: ["zhun", "chun"],
    category: "vocabulary",
    gloss: "accurate, spot-on, excellent",
    stance: null,
    valenceShift: 0.3,
    arousalShift: 0.1,
    masksDistress: false,
  },
  {
    token: "terok",
    variants: ["terok", "teruk"],
    category: "vocabulary",
    gloss: "terrible, in a bad state — often understating how bad things actually are",
    stance: null,
    valenceShift: -0.5,
    arousalShift: 0.1,
    masksDistress: true,
  },
  {
    token: "gostan",
    variants: ["gostan"],
    category: "vocabulary",
    gloss: "to reverse/back up (from 'go astern') — neutral, practical",
    stance: null,
    valenceShift: 0,
    arousalShift: 0,
    masksDistress: false,
  },
  {
    token: "chiong",
    variants: ["chiong", "chiong sua"],
    category: "vocabulary",
    gloss: "to rush/charge ahead, push hard — can be enthusiasm or exhausted grinding",
    stance: null,
    valenceShift: 0.05,
    arousalShift: 0.4,
    masksDistress: false,
  },
  {
    token: "action",
    variants: ["action", "acting", "act blur"],
    category: "vocabulary",
    gloss: "putting on airs, pretending, showing off (as in 'why you so action')",
    stance: null,
    valenceShift: -0.15,
    arousalShift: 0.1,
    masksDistress: false,
  },
  {
    token: "spoil market",
    variants: ["spoil market", "spoiled market"],
    category: "vocabulary",
    gloss: "to set an unreasonable standard others now feel pressured to match",
    stance: null,
    valenceShift: -0.05,
    arousalShift: 0.1,
    masksDistress: false,
  },
  {
    token: "makan",
    variants: ["makan", "makan already"],
    category: "vocabulary",
    gloss: "to eat / a meal — neutral",
    stance: null,
    valenceShift: 0,
    arousalShift: 0,
    masksDistress: false,
  },
  {
    token: "tapau",
    variants: ["tapau", "da bao"],
    category: "vocabulary",
    gloss: "to pack food to go — neutral, practical",
    stance: null,
    valenceShift: 0,
    arousalShift: 0,
    masksDistress: false,
  },
  {
    token: "swee",
    variants: ["swee", "shweet"],
    category: "vocabulary",
    gloss: "nice, great, pleasing outcome",
    stance: null,
    valenceShift: 0.4,
    arousalShift: 0.2,
    masksDistress: false,
  },
  {
    token: "whack",
    variants: ["whack", "wack"],
    category: "vocabulary",
    gloss: "to attack/criticise heavily, or to dig into food enthusiastically depending on context",
    stance: null,
    valenceShift: -0.1,
    arousalShift: 0.3,
    masksDistress: false,
  },
  {
    token: "onz",
    variants: ["onz", "on"],
    category: "vocabulary",
    gloss: "'deal/agreed', enthusiastic confirmation",
    stance: null,
    valenceShift: 0.3,
    arousalShift: 0.2,
    masksDistress: false,
  },
  {
    token: "garang",
    variants: ["garang"],
    category: "vocabulary",
    gloss: "fierce, gung-ho, unafraid to push hard",
    stance: null,
    valenceShift: 0.1,
    arousalShift: 0.35,
    masksDistress: false,
  },

  // ── Aspect markers ───────────────────────────────────────────────────────
  {
    token: "already",
    variants: ["already", "liao"],
    category: "aspect",
    gloss: "completive aspect marker — signals a past/completed action or state, e.g. 'I try already' = a past coping attempt, NOT future intent",
    stance: "completive",
    valenceShift: 0,
    arousalShift: 0,
    masksDistress: false,
  },
  {
    token: "got",
    variants: ["got"],
    category: "aspect",
    gloss: "perfective marker in questions/statements ('you got eat?' = 'have you eaten?') — NOT possession",
    stance: "perfective",
    valenceShift: 0,
    arousalShift: 0,
    masksDistress: false,
  },
  {
    token: "never",
    variants: ["never"],
    category: "aspect",
    gloss: "negative past-tense marker ('I never reply you' = 'I did not reply you') — NOT an absolutist claim about all time, do not conflate with the English adverb 'never'",
    stance: "negative-past",
    valenceShift: -0.1,
    arousalShift: 0,
    masksDistress: false,
  },

  // ── Reduplication ────────────────────────────────────────────────────────
  {
    token: "talk talk only",
    variants: ["talk talk only", "say say only", "look look only"],
    category: "reduplication",
    gloss: "reduplication marking dismissiveness/triviality register ('just talk, nothing more/nothing real') — a tokenizer reads this as a disfluency, but it is a deliberate register shift, often minimising something that matters",
    stance: "dismissive-minimising",
    valenceShift: -0.2,
    arousalShift: -0.1,
    masksDistress: true,
  },
]);

/** Flattened lookup: every surface form (token + all variants) to its entry. */
export const SINGLISH_SURFACE_FORMS = Object.freeze(
  SINGLISH_LEXICON.flatMap((entry) => [entry.token, ...entry.variants].map((surface) => ({ surface, entry })))
);

/**
 * Surface forms that also occur, with an entirely different meaning, in
 * ordinary English. Without this list the variety detector fires on plain
 * English sentences — "I got a lot done already and one thing still bugs me"
 * matches got + already + one and would be scored as Singlish, with
 * "never" then read as a past-tense marker rather than the English adverb.
 *
 * dialect/index.js uses this two ways:
 *   1. these forms never contribute evidence toward IDENTIFYING the variety;
 *   2. their valence/arousal shifts are only applied once the variety has
 *      been confirmed by at least one distinctive (strong-signal) form.
 *
 * The cost of that rule is a few missed adjustments in a short Singlish
 * entry that happens to use only ambiguous tokens. The cost of NOT having it
 * is silently mis-scoring every plain-English entry that says "got" — a much
 * larger and much less visible error.
 */
export const SINGLISH_AMBIGUOUS_SURFACE_FORMS = Object.freeze([
  "la", "ah", "one", "meh", "seh", "on", "chop", "blur", "shag", "shagged",
  "wah", "wahh",
  "steady", "action", "acting", "whack", "wack", "already", "got", "never",
  "never mind", "used to it", "cannot make it", "cant make it", "can't make it",
  "spoil market", "spoiled market",
]);

/**
 * Syntactic signatures: CONSTRUCTIONS that are ungrammatical (or mean
 * something else) in standard English, and therefore identify the variety
 * even when every word in them is an ordinary English word.
 *
 * This is what makes "You got eat?" and "I try already" detectable without
 * putting the bare words "got" and "already" into the evidence pool — the
 * evidence is the pattern, not the token. Each entry names the lexicon token
 * the pattern confirms, so a matched pattern both identifies the variety and
 * unlocks that token's gloss.
 */
export const SINGLISH_SYNTACTIC_PATTERNS = Object.freeze([
  {
    id: "got-perfective",
    token: "got",
    // "got" + bare verb: perfective, not possession.
    pattern: /\bgot\s+(eat|go|see|come|do|make|take|sleep|study|work|try|buy|bring|say|meet|call|send|finish|reply|watch|use)\b/i,
  },
  {
    id: "already-completive",
    token: "already",
    // bare present-tense verb + "already": completive aspect, ungrammatical
    // in standard English, which would require a perfect or past form.
    pattern: /\b(try|eat|go|come|do|finish|reach|sleep|start|send|pay|book|buy|reply|tell|ask|settle|cancel|apply|submit)\s+already\b/i,
  },
  {
    id: "liao-completive",
    token: "already",
    pattern: /\bliao\b/i,
  },
  {
    id: "never-negative-past",
    token: "never",
    // object-dropping "never <verb> <pronoun>": negative past, not the
    // English habitual adverb ("I never reply you" vs "I never reply to you").
    pattern: /\bnever\s+(reply|call|text|message|tell|ask|inform|update|answer|return|pass|send)\s+(you|me|him|her|them|us)\b/i,
  },
  {
    id: "emphatic-nominaliser-one",
    token: "one",
    // "<intensifier> <adjective> one": clause-final nominaliser.
    pattern: /\b(very|so|damn|too|super)\s+[a-z]+\s+one\b/i,
  },
]);
